"""Update date field name

Revision ID: 0244e20c01d7
Revises: 58ec821330c5
Create Date: 2025-03-11 12:23:54.827256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0244e20c01d7'
down_revision: Union[str, None] = '58ec821330c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('reported_date', sa.DateTime(), nullable=True))
    op.drop_column('submission', 'reported_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('reported_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('submission', 'reported_date')
    # ### end Alembic commands ###
