"""Add points to submission

Revision ID: 0cbedd4f2f05
Revises: 2acdc2e59036
Create Date: 2025-03-28 00:19:57.890985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbedd4f2f05'
down_revision: Union[str, None] = '2acdc2e59036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'points')
    # ### end Alembic commands ###
