"""Add rank to league run

Revision ID: 14c09d0b2be4
Revises: 2cc740ec769f
Create Date: 2025-06-09 10:35:17.829622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c09d0b2be4'
down_revision: Union[str, None] = '2cc740ec769f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_run', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_run', 'rank')
    # ### end Alembic commands ###
