"""Add username color

Revision ID: 2acdc2e59036
Revises: a80dfa80644b
Create Date: 2025-03-24 15:03:14.618471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2acdc2e59036'
down_revision: Union[str, None] = 'a80dfa80644b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username_color')
    # ### end Alembic commands ###
