"""add rank to submission table

Revision ID: 2c1c60a641dc
Revises: 8f291bd7c003
Create Date: 2025-02-24 21:17:24.282463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1c60a641dc'
down_revision: Union[str, None] = '8f291bd7c003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'rank')
    # ### end Alembic commands ###
