"""Add table for multiple users to one badge

Revision ID: 42b7cf356fa1
Revises: 5811a7181b8e
Create Date: 2025-11-16 19:41:24.758829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42b7cf356fa1'
down_revision: Union[str, None] = '5811a7181b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_badges',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    op.drop_constraint('badge_user_id_fkey', 'badge', type_='foreignkey')
    op.drop_column('badge', 'user_id')
    op.drop_column('badge', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('badge', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('badge_user_id_fkey', 'badge', 'user', ['user_id'], ['id'])
    op.drop_table('user_badges')
    # ### end Alembic commands ###
