"""Add reported to submission and role to user

Revision ID: 43edf7215765
Revises: 968ac15c3f97
Create Date: 2025-03-05 13:17:11.603405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43edf7215765'
down_revision: Union[str, None] = '968ac15c3f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('reported', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('flag', sa.String(length=4), nullable=True))
    op.add_column('user', sa.Column('lb_pref', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lb_pref')
    op.drop_column('user', 'flag')
    op.drop_column('user', 'role')
    op.drop_column('submission', 'reported')
    # ### end Alembic commands ###
