"""Update badge with url

Revision ID: 5811a7181b8e
Revises: e6da07cd5a74
Create Date: 2025-11-16 18:25:09.365282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5811a7181b8e'
down_revision: Union[str, None] = 'e6da07cd5a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge', 'url')
    # ### end Alembic commands ###
