"""Add submission report fields

Revision ID: 58ec821330c5
Revises: 971f43f50836
Create Date: 2025-03-11 12:22:54.613685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ec821330c5'
down_revision: Union[str, None] = '971f43f50836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('reported_data', sa.DateTime(), nullable=True))
    op.add_column('submission', sa.Column('reported_message', sa.String(length=255), nullable=True))
    op.add_column('submission', sa.Column('reported_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submission', 'user', ['reported_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_column('submission', 'reported_by')
    op.drop_column('submission', 'reported_message')
    op.drop_column('submission', 'reported_data')
    # ### end Alembic commands ###
