"""Add game title submission

Revision ID: 8f291bd7c003
Revises: 9662e4b7b91b
Create Date: 2025-02-13 14:00:58.518630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f291bd7c003'
down_revision: Union[str, None] = '9662e4b7b91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('game_title', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'game_title')
    # ### end Alembic commands ###
