"""Add user backgroun page color

Revision ID: 968ac15c3f97
Revises: 2c1c60a641dc
Create Date: 2025-02-25 13:26:23.739099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968ac15c3f97'
down_revision: Union[str, None] = '2c1c60a641dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('background_page_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'background_page_color')
    # ### end Alembic commands ###
