"""Add submission fields

Revision ID: 971f43f50836
Revises: e5a1f2322f99
Create Date: 2025-03-11 12:11:55.905037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971f43f50836'
down_revision: Union[str, None] = 'e5a1f2322f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('voided', sa.Boolean(), nullable=True))
    op.add_column('submission', sa.Column('highlighted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('pronouns', sa.Integer(), nullable=True))
    op.drop_column('user', 'background_page_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('background_page_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.drop_column('user', 'pronouns')
    op.drop_column('submission', 'highlighted')
    op.drop_column('submission', 'voided')
    # ### end Alembic commands ###
