"""Added description to submission

Revision ID: a80dfa80644b
Revises: f3c08a7f5e87
Create Date: 2025-03-18 20:18:54.023132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80dfa80644b'
down_revision: Union[str, None] = 'f3c08a7f5e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'description')
    # ### end Alembic commands ###
