"""Added Badges to database

Revision ID: e6da07cd5a74
Revises: e8af5bca1982
Create Date: 2025-11-16 18:23:42.693727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6da07cd5a74'
down_revision: Union[str, None] = 'e8af5bca1982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge', 'date')
    # ### end Alembic commands ###
